[package]
name = "manicscrobbler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
floem = "0.1.1"
rspotify = "0.13.2"
notion = "0.5.1"